{
    "patcher": {
        "fileversion": 1,
        "appversion": { "major": 9, "minor": 1, "revision": 0, "architecture": "x64", "modernui": 1 },
        "classnamespace": "box",
        "rect": [ 34.0, 80.0, 1400.0, 950.0 ],
        "bglocked": 0,
        "openinpresentation": 0,
        "boxes": [
            { "box": { "id": "obj-title", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [ 30.0, 10.0, 500.0, 20.0 ], "text": "SPHINXHARM SPECTRAL — pfft~/gizmo~ 4-voice harmonizer with formant EQ", "fontsize": 13, "fontface": 1 } },
            { "box": { "id": "obj-subtitle", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [ 30.0, 30.0, 600.0, 20.0 ], "text": "Upgrade: spectral pitch shift (gizmo~) replaces gen~ granular. Tilt EQ for formant shaping." } },

            { "box": { "id": "obj-adc", "maxclass": "newobj", "numinlets": 1, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 50.0, 60.0, 45.0, 22.0 ], "text": "adc~ 1" } },
            { "box": { "id": "obj-in-meter", "maxclass": "meter~", "numinlets": 1, "numoutlets": 1, "outlettype": [ "float" ], "patching_rect": [ 110.0, 62.0, 100.0, 14.0 ] } },

            { "box": { "id": "obj-loadbang", "maxclass": "newobj", "numinlets": 1, "numoutlets": 1, "outlettype": [ "bang" ], "patching_rect": [ 1100.0, 60.0, 58.0, 22.0 ], "text": "loadbang" } },
            { "box": { "id": "obj-init-msg", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 1100.0, 90.0, 18.0, 22.0 ], "text": "0" } },
            { "box": { "id": "obj-sig1", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 1100.0, 430.0, 42.0, 22.0 ], "text": "sig~ 1." } },

            { "box": { "id": "obj-v1-lbl", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [ 30.0, 90.0, 100.0, 20.0 ], "text": "VOICE 1", "fontface": 1 } },
            { "box": { "id": "obj-v1-slbl", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [ 30.0, 108.0, 280.0, 20.0 ], "text": "semi / formant / gain(dB) / delay(ms) / pan(-1..1)" } },
            { "box": { "id": "obj-v1-semi", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 30.0, 130.0, 50.0, 22.0 ], "minimum": -24.0, "maximum": 24.0 } },
            { "box": { "id": "obj-v1-fmt", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 85.0, 130.0, 50.0, 22.0 ], "minimum": -24.0, "maximum": 24.0 } },
            { "box": { "id": "obj-v1-gain", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 140.0, 130.0, 50.0, 22.0 ] } },
            { "box": { "id": "obj-v1-dly", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 195.0, 130.0, 50.0, 22.0 ], "minimum": 0.0, "maximum": 2000.0 } },
            { "box": { "id": "obj-v1-pan", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 250.0, 130.0, 50.0, 22.0 ], "minimum": -1.0, "maximum": 1.0 } },

            { "box": { "id": "obj-v1-ratio", "maxclass": "newobj", "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 30.0, 160.0, 128.0, 22.0 ], "text": "expr pow(2.\\, $f1/12.)" } },
            { "box": { "id": "obj-v1-fmtsig", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 85.0, 160.0, 32.0, 22.0 ], "text": "sig~" } },

            { "box": { "id": "obj-v1-pfft", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 30.0, 195.0, 230.0, 22.0 ], "text": "pfft~ spectral_voice_fft 2048 4" } },

            { "box": { "id": "obj-v1-fmteq", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 30.0, 225.0, 130.0, 22.0 ], "text": "gen~ @gen formant_eq" } },

            { "box": { "id": "obj-v1-dbtoa", "maxclass": "newobj", "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 140.0, 160.0, 38.0, 22.0 ], "text": "dbtoa" } },
            { "box": { "id": "obj-v1-mult", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 30.0, 255.0, 40.0, 22.0 ], "text": "*~ 1." } },

            { "box": { "id": "obj-v1-dlysig", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 195.0, 160.0, 32.0, 22.0 ], "text": "sig~" } },
            { "box": { "id": "obj-v1-ms2s", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 195.0, 185.0, 45.0, 22.0 ], "text": "*~ 44.1" } },
            { "box": { "id": "obj-v1-delay", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 30.0, 285.0, 75.0, 22.0 ], "text": "delay~ 88200" } },

            { "box": { "id": "obj-v1-ps", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 250.0, 160.0, 32.0, 22.0 ], "text": "sig~" } },
            { "box": { "id": "obj-v1-phalf", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 250.0, 190.0, 40.0, 22.0 ], "text": "*~ 0.5" } },
            { "box": { "id": "obj-v1-poff", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 250.0, 215.0, 40.0, 22.0 ], "text": "+~ 0.5" } },
            { "box": { "id": "obj-v1-invp", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 250.0, 240.0, 50.0, 22.0 ], "text": "!-~ 1." } },
            { "box": { "id": "obj-v1-panR", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 30.0, 315.0, 30.0, 22.0 ], "text": "*~" } },
            { "box": { "id": "obj-v1-panL", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 130.0, 315.0, 30.0, 22.0 ], "text": "*~" } },

            { "box": { "id": "obj-v2-lbl", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [ 350.0, 90.0, 100.0, 20.0 ], "text": "VOICE 2", "fontface": 1 } },
            { "box": { "id": "obj-v2-slbl", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [ 350.0, 108.0, 280.0, 20.0 ], "text": "semi / formant / gain(dB) / delay(ms) / pan(-1..1)" } },
            { "box": { "id": "obj-v2-semi", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 350.0, 130.0, 50.0, 22.0 ], "minimum": -24.0, "maximum": 24.0 } },
            { "box": { "id": "obj-v2-fmt", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 405.0, 130.0, 50.0, 22.0 ], "minimum": -24.0, "maximum": 24.0 } },
            { "box": { "id": "obj-v2-gain", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 460.0, 130.0, 50.0, 22.0 ] } },
            { "box": { "id": "obj-v2-dly", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 515.0, 130.0, 50.0, 22.0 ], "minimum": 0.0, "maximum": 2000.0 } },
            { "box": { "id": "obj-v2-pan", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 570.0, 130.0, 50.0, 22.0 ], "minimum": -1.0, "maximum": 1.0 } },

            { "box": { "id": "obj-v2-ratio", "maxclass": "newobj", "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 350.0, 160.0, 128.0, 22.0 ], "text": "expr pow(2.\\, $f1/12.)" } },
            { "box": { "id": "obj-v2-fmtsig", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 405.0, 160.0, 32.0, 22.0 ], "text": "sig~" } },
            { "box": { "id": "obj-v2-pfft", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 350.0, 195.0, 230.0, 22.0 ], "text": "pfft~ spectral_voice_fft 2048 4" } },
            { "box": { "id": "obj-v2-fmteq", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 350.0, 225.0, 130.0, 22.0 ], "text": "gen~ @gen formant_eq" } },
            { "box": { "id": "obj-v2-dbtoa", "maxclass": "newobj", "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 460.0, 160.0, 38.0, 22.0 ], "text": "dbtoa" } },
            { "box": { "id": "obj-v2-mult", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 350.0, 255.0, 40.0, 22.0 ], "text": "*~ 1." } },
            { "box": { "id": "obj-v2-dlysig", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 515.0, 160.0, 32.0, 22.0 ], "text": "sig~" } },
            { "box": { "id": "obj-v2-ms2s", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 515.0, 185.0, 45.0, 22.0 ], "text": "*~ 44.1" } },
            { "box": { "id": "obj-v2-delay", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 350.0, 285.0, 75.0, 22.0 ], "text": "delay~ 88200" } },
            { "box": { "id": "obj-v2-ps", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 570.0, 160.0, 32.0, 22.0 ], "text": "sig~" } },
            { "box": { "id": "obj-v2-phalf", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 570.0, 190.0, 40.0, 22.0 ], "text": "*~ 0.5" } },
            { "box": { "id": "obj-v2-poff", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 570.0, 215.0, 40.0, 22.0 ], "text": "+~ 0.5" } },
            { "box": { "id": "obj-v2-invp", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 570.0, 240.0, 50.0, 22.0 ], "text": "!-~ 1." } },
            { "box": { "id": "obj-v2-panR", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 350.0, 315.0, 30.0, 22.0 ], "text": "*~" } },
            { "box": { "id": "obj-v2-panL", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 450.0, 315.0, 30.0, 22.0 ], "text": "*~" } },

            { "box": { "id": "obj-v3-lbl", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [ 30.0, 345.0, 100.0, 20.0 ], "text": "VOICE 3", "fontface": 1 } },
            { "box": { "id": "obj-v3-slbl", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [ 30.0, 363.0, 280.0, 20.0 ], "text": "semi / formant / gain(dB) / delay(ms) / pan(-1..1)" } },
            { "box": { "id": "obj-v3-semi", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 30.0, 385.0, 50.0, 22.0 ], "minimum": -24.0, "maximum": 24.0 } },
            { "box": { "id": "obj-v3-fmt", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 85.0, 385.0, 50.0, 22.0 ], "minimum": -24.0, "maximum": 24.0 } },
            { "box": { "id": "obj-v3-gain", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 140.0, 385.0, 50.0, 22.0 ] } },
            { "box": { "id": "obj-v3-dly", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 195.0, 385.0, 50.0, 22.0 ], "minimum": 0.0, "maximum": 2000.0 } },
            { "box": { "id": "obj-v3-pan", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 250.0, 385.0, 50.0, 22.0 ], "minimum": -1.0, "maximum": 1.0 } },

            { "box": { "id": "obj-v3-ratio", "maxclass": "newobj", "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 30.0, 415.0, 128.0, 22.0 ], "text": "expr pow(2.\\, $f1/12.)" } },
            { "box": { "id": "obj-v3-fmtsig", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 85.0, 415.0, 32.0, 22.0 ], "text": "sig~" } },
            { "box": { "id": "obj-v3-pfft", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 30.0, 450.0, 230.0, 22.0 ], "text": "pfft~ spectral_voice_fft 2048 4" } },
            { "box": { "id": "obj-v3-fmteq", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 30.0, 480.0, 130.0, 22.0 ], "text": "gen~ @gen formant_eq" } },
            { "box": { "id": "obj-v3-dbtoa", "maxclass": "newobj", "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 140.0, 415.0, 38.0, 22.0 ], "text": "dbtoa" } },
            { "box": { "id": "obj-v3-mult", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 30.0, 510.0, 40.0, 22.0 ], "text": "*~ 1." } },
            { "box": { "id": "obj-v3-dlysig", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 195.0, 415.0, 32.0, 22.0 ], "text": "sig~" } },
            { "box": { "id": "obj-v3-ms2s", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 195.0, 440.0, 45.0, 22.0 ], "text": "*~ 44.1" } },
            { "box": { "id": "obj-v3-delay", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 30.0, 540.0, 75.0, 22.0 ], "text": "delay~ 88200" } },
            { "box": { "id": "obj-v3-ps", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 250.0, 415.0, 32.0, 22.0 ], "text": "sig~" } },
            { "box": { "id": "obj-v3-phalf", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 250.0, 445.0, 40.0, 22.0 ], "text": "*~ 0.5" } },
            { "box": { "id": "obj-v3-poff", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 250.0, 470.0, 40.0, 22.0 ], "text": "+~ 0.5" } },
            { "box": { "id": "obj-v3-invp", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 250.0, 495.0, 50.0, 22.0 ], "text": "!-~ 1." } },
            { "box": { "id": "obj-v3-panR", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 30.0, 570.0, 30.0, 22.0 ], "text": "*~" } },
            { "box": { "id": "obj-v3-panL", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 130.0, 570.0, 30.0, 22.0 ], "text": "*~" } },

            { "box": { "id": "obj-v4-lbl", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [ 350.0, 345.0, 100.0, 20.0 ], "text": "VOICE 4", "fontface": 1 } },
            { "box": { "id": "obj-v4-slbl", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [ 350.0, 363.0, 280.0, 20.0 ], "text": "semi / formant / gain(dB) / delay(ms) / pan(-1..1)" } },
            { "box": { "id": "obj-v4-semi", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 350.0, 385.0, 50.0, 22.0 ], "minimum": -24.0, "maximum": 24.0 } },
            { "box": { "id": "obj-v4-fmt", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 405.0, 385.0, 50.0, 22.0 ], "minimum": -24.0, "maximum": 24.0 } },
            { "box": { "id": "obj-v4-gain", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 460.0, 385.0, 50.0, 22.0 ] } },
            { "box": { "id": "obj-v4-dly", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 515.0, 385.0, 50.0, 22.0 ], "minimum": 0.0, "maximum": 2000.0 } },
            { "box": { "id": "obj-v4-pan", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 570.0, 385.0, 50.0, 22.0 ], "minimum": -1.0, "maximum": 1.0 } },

            { "box": { "id": "obj-v4-ratio", "maxclass": "newobj", "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 350.0, 415.0, 128.0, 22.0 ], "text": "expr pow(2.\\, $f1/12.)" } },
            { "box": { "id": "obj-v4-fmtsig", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 405.0, 415.0, 32.0, 22.0 ], "text": "sig~" } },
            { "box": { "id": "obj-v4-pfft", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 350.0, 450.0, 230.0, 22.0 ], "text": "pfft~ spectral_voice_fft 2048 4" } },
            { "box": { "id": "obj-v4-fmteq", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 350.0, 480.0, 130.0, 22.0 ], "text": "gen~ @gen formant_eq" } },
            { "box": { "id": "obj-v4-dbtoa", "maxclass": "newobj", "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 460.0, 415.0, 38.0, 22.0 ], "text": "dbtoa" } },
            { "box": { "id": "obj-v4-mult", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 350.0, 510.0, 40.0, 22.0 ], "text": "*~ 1." } },
            { "box": { "id": "obj-v4-dlysig", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 515.0, 415.0, 32.0, 22.0 ], "text": "sig~" } },
            { "box": { "id": "obj-v4-ms2s", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 515.0, 440.0, 45.0, 22.0 ], "text": "*~ 44.1" } },
            { "box": { "id": "obj-v4-delay", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 350.0, 540.0, 75.0, 22.0 ], "text": "delay~ 88200" } },
            { "box": { "id": "obj-v4-ps", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 570.0, 415.0, 32.0, 22.0 ], "text": "sig~" } },
            { "box": { "id": "obj-v4-phalf", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 570.0, 445.0, 40.0, 22.0 ], "text": "*~ 0.5" } },
            { "box": { "id": "obj-v4-poff", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 570.0, 470.0, 40.0, 22.0 ], "text": "+~ 0.5" } },
            { "box": { "id": "obj-v4-invp", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 570.0, 495.0, 50.0, 22.0 ], "text": "!-~ 1." } },
            { "box": { "id": "obj-v4-panR", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 350.0, 570.0, 30.0, 22.0 ], "text": "*~" } },
            { "box": { "id": "obj-v4-panL", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 450.0, 570.0, 30.0, 22.0 ], "text": "*~" } },

            { "box": { "id": "obj-dry-lbl", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [ 700.0, 90.0, 100.0, 20.0 ], "text": "DRY", "fontface": 1 } },
            { "box": { "id": "obj-dry-gain", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 700.0, 110.0, 50.0, 22.0 ] } },
            { "box": { "id": "obj-dry-dbtoa", "maxclass": "newobj", "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 700.0, 140.0, 38.0, 22.0 ], "text": "dbtoa" } },
            { "box": { "id": "obj-dry-mult", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 700.0, 170.0, 40.0, 22.0 ], "text": "*~ 1." } },

            { "box": { "id": "obj-master-lbl", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [ 700.0, 210.0, 100.0, 20.0 ], "text": "MASTER", "fontface": 1 } },
            { "box": { "id": "obj-master-val", "maxclass": "flonum", "numinlets": 1, "numoutlets": 2, "outlettype": [ "", "bang" ], "patching_rect": [ 700.0, 230.0, 50.0, 22.0 ] } },
            { "box": { "id": "obj-master-dbtoa", "maxclass": "newobj", "numinlets": 1, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 700.0, 260.0, 38.0, 22.0 ], "text": "dbtoa" } },

            { "box": { "id": "obj-key-lbl", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [ 700.0, 310.0, 160.0, 20.0 ], "text": "KEY / SCALE", "fontface": 1 } },
            { "box": { "id": "obj-key-menu", "maxclass": "umenu", "numinlets": 1, "numoutlets": 3, "outlettype": [ "int", "", "" ], "patching_rect": [ 700.0, 335.0, 70.0, 22.0 ], "items": [ "C", ",", "C#", ",", "D", ",", "Eb", ",", "E", ",", "F", ",", "F#", ",", "G", ",", "Ab", ",", "A", ",", "Bb", ",", "B" ] } },
            { "box": { "id": "obj-scale-menu", "maxclass": "umenu", "numinlets": 1, "numoutlets": 3, "outlettype": [ "int", "", "" ], "patching_rect": [ 780.0, 335.0, 100.0, 22.0 ], "items": [ "Major", ",", "Minor", ",", "Dorian", ",", "Mixolydian", ",", "Pent Maj", ",", "Pent Min", ",", "Chromatic" ] } },
            { "box": { "id": "obj-harmony", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 700.0, 370.0, 140.0, 22.0 ], "text": "js harmony_engine.js" } },

            { "box": { "id": "obj-preset-lbl", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [ 700.0, 410.0, 160.0, 20.0 ], "text": "PRESETS", "fontface": 1 } },
            { "box": { "id": "obj-preset-woods", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 700.0, 435.0, 50.0, 22.0 ], "text": "bang" } },
            { "box": { "id": "obj-preset-choir", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 755.0, 435.0, 50.0, 22.0 ], "text": "bang" } },
            { "box": { "id": "obj-preset-shimmer", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 810.0, 435.0, 55.0, 22.0 ], "text": "bang" } },
            { "box": { "id": "obj-preset-dark", "maxclass": "message", "numinlets": 2, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 870.0, 435.0, 50.0, 22.0 ], "text": "bang" } },
            { "box": { "id": "obj-plbl-w", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [ 700.0, 458.0, 50.0, 20.0 ], "text": "Woods" } },
            { "box": { "id": "obj-plbl-c", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [ 755.0, 458.0, 50.0, 20.0 ], "text": "Choir" } },
            { "box": { "id": "obj-plbl-s", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [ 810.0, 458.0, 55.0, 20.0 ], "text": "Shimmer" } },
            { "box": { "id": "obj-plbl-d", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [ 870.0, 458.0, 50.0, 20.0 ], "text": "Dark" } },
            { "box": { "id": "obj-presets", "maxclass": "newobj", "numinlets": 4, "numoutlets": 1, "outlettype": [ "" ], "patching_rect": [ 700.0, 485.0, 160.0, 22.0 ], "text": "js preset_handler.js" } },
            { "box": { "id": "obj-route-presets", "maxclass": "newobj", "numinlets": 1, "numoutlets": 22, "outlettype": [ "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "" ], "patching_rect": [ 700.0, 515.0, 600.0, 22.0 ], "text": "route v1_semi v2_semi v3_semi v4_semi v1_formant v2_formant v3_formant v4_formant v1_gain v2_gain v3_gain v4_gain v1_delay v2_delay v3_delay v4_delay v1_pan v2_pan v3_pan v4_pan dry_gain" } },

            { "box": { "id": "obj-lbl-left", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [ 200.0, 610.0, 40.0, 20.0 ], "text": "LEFT" } },
            { "box": { "id": "obj-lbl-right", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [ 350.0, 610.0, 50.0, 20.0 ], "text": "RIGHT" } },

            { "box": { "id": "obj-sumL1", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 200.0, 630.0, 30.0, 22.0 ], "text": "+~" } },
            { "box": { "id": "obj-sumL2", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 200.0, 660.0, 30.0, 22.0 ], "text": "+~" } },
            { "box": { "id": "obj-sumL3", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 200.0, 690.0, 30.0, 22.0 ], "text": "+~" } },
            { "box": { "id": "obj-sumR1", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 350.0, 630.0, 30.0, 22.0 ], "text": "+~" } },
            { "box": { "id": "obj-sumR2", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 350.0, 660.0, 30.0, 22.0 ], "text": "+~" } },
            { "box": { "id": "obj-sumR3", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 350.0, 690.0, 30.0, 22.0 ], "text": "+~" } },

            { "box": { "id": "obj-addDryL", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 200.0, 730.0, 30.0, 22.0 ], "text": "+~" } },
            { "box": { "id": "obj-addDryR", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 350.0, 730.0, 30.0, 22.0 ], "text": "+~" } },

            { "box": { "id": "obj-masterL", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 200.0, 770.0, 40.0, 22.0 ], "text": "*~ 1." } },
            { "box": { "id": "obj-masterR", "maxclass": "newobj", "numinlets": 2, "numoutlets": 1, "outlettype": [ "signal" ], "patching_rect": [ 350.0, 770.0, 40.0, 22.0 ], "text": "*~ 1." } },

            { "box": { "id": "obj-meterL", "maxclass": "meter~", "numinlets": 1, "numoutlets": 1, "outlettype": [ "float" ], "patching_rect": [ 200.0, 810.0, 100.0, 14.0 ] } },
            { "box": { "id": "obj-meterR", "maxclass": "meter~", "numinlets": 1, "numoutlets": 1, "outlettype": [ "float" ], "patching_rect": [ 350.0, 810.0, 100.0, 14.0 ] } },
            { "box": { "id": "obj-ezdac", "maxclass": "ezdac~", "numinlets": 2, "numoutlets": 0, "patching_rect": [ 260.0, 840.0, 45.0, 45.0 ] } },

            { "box": { "id": "obj-info1", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [ 700.0, 560.0, 350.0, 20.0 ], "text": "SIGNAL FLOW:" } },
            { "box": { "id": "obj-info2", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [ 700.0, 580.0, 380.0, 20.0 ], "text": "adc~ -> pfft~/gizmo~ (pitch) -> formant_eq (tilt) -> gain -> pan" } },
            { "box": { "id": "obj-info3", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [ 700.0, 600.0, 380.0, 20.0 ], "text": "Formant tilt: +semi=brighter -semi=darker 0=transparent" } },
            { "box": { "id": "obj-info4", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [ 700.0, 620.0, 380.0, 20.0 ], "text": "FFT: 2048pt overlap 4 (~46ms latency). Change to 4096 for quality." } },
            { "box": { "id": "obj-info5", "maxclass": "comment", "numinlets": 1, "numoutlets": 0, "patching_rect": [ 700.0, 640.0, 380.0, 20.0 ], "text": "UPGRADE: Install FFTease, replace formant_eq with mindwarp~" } }
        ],
        "lines": [
            { "patchline": { "source": [ "obj-adc", 0 ], "destination": [ "obj-in-meter", 0 ] } },
            { "patchline": { "source": [ "obj-adc", 0 ], "destination": [ "obj-v1-pfft", 0 ] } },
            { "patchline": { "source": [ "obj-adc", 0 ], "destination": [ "obj-v2-pfft", 0 ] } },
            { "patchline": { "source": [ "obj-adc", 0 ], "destination": [ "obj-v3-pfft", 0 ] } },
            { "patchline": { "source": [ "obj-adc", 0 ], "destination": [ "obj-v4-pfft", 0 ] } },
            { "patchline": { "source": [ "obj-adc", 0 ], "destination": [ "obj-dry-mult", 0 ] } },

            { "patchline": { "source": [ "obj-loadbang", 0 ], "destination": [ "obj-init-msg", 0 ] } },
            { "patchline": { "source": [ "obj-init-msg", 0 ], "destination": [ "obj-v1-pan", 0 ] } },
            { "patchline": { "source": [ "obj-init-msg", 0 ], "destination": [ "obj-v2-pan", 0 ] } },
            { "patchline": { "source": [ "obj-init-msg", 0 ], "destination": [ "obj-v3-pan", 0 ] } },
            { "patchline": { "source": [ "obj-init-msg", 0 ], "destination": [ "obj-v4-pan", 0 ] } },

            { "patchline": { "source": [ "obj-v1-semi", 0 ], "destination": [ "obj-v1-ratio", 0 ] } },
            { "patchline": { "source": [ "obj-v1-ratio", 0 ], "destination": [ "obj-v1-pfft", 1 ] } },
            { "patchline": { "source": [ "obj-v1-pfft", 0 ], "destination": [ "obj-v1-fmteq", 0 ] } },
            { "patchline": { "source": [ "obj-v1-fmt", 0 ], "destination": [ "obj-v1-fmtsig", 0 ] } },
            { "patchline": { "source": [ "obj-v1-fmtsig", 0 ], "destination": [ "obj-v1-fmteq", 1 ] } },
            { "patchline": { "source": [ "obj-v1-fmteq", 0 ], "destination": [ "obj-v1-mult", 0 ] } },
            { "patchline": { "source": [ "obj-v1-gain", 0 ], "destination": [ "obj-v1-dbtoa", 0 ] } },
            { "patchline": { "source": [ "obj-v1-dbtoa", 0 ], "destination": [ "obj-v1-mult", 1 ] } },
            { "patchline": { "source": [ "obj-v1-mult", 0 ], "destination": [ "obj-v1-delay", 0 ] } },
            { "patchline": { "source": [ "obj-v1-dly", 0 ], "destination": [ "obj-v1-dlysig", 0 ] } },
            { "patchline": { "source": [ "obj-v1-dlysig", 0 ], "destination": [ "obj-v1-ms2s", 0 ] } },
            { "patchline": { "source": [ "obj-v1-ms2s", 0 ], "destination": [ "obj-v1-delay", 1 ] } },
            { "patchline": { "source": [ "obj-v1-pan", 0 ], "destination": [ "obj-v1-ps", 0 ] } },
            { "patchline": { "source": [ "obj-v1-ps", 0 ], "destination": [ "obj-v1-phalf", 0 ] } },
            { "patchline": { "source": [ "obj-v1-phalf", 0 ], "destination": [ "obj-v1-poff", 0 ] } },
            { "patchline": { "source": [ "obj-v1-poff", 0 ], "destination": [ "obj-v1-panR", 1 ] } },
            { "patchline": { "source": [ "obj-v1-poff", 0 ], "destination": [ "obj-v1-invp", 0 ] } },
            { "patchline": { "source": [ "obj-v1-invp", 0 ], "destination": [ "obj-v1-panL", 1 ] } },
            { "patchline": { "source": [ "obj-v1-delay", 0 ], "destination": [ "obj-v1-panR", 0 ] } },
            { "patchline": { "source": [ "obj-v1-delay", 0 ], "destination": [ "obj-v1-panL", 0 ] } },

            { "patchline": { "source": [ "obj-v2-semi", 0 ], "destination": [ "obj-v2-ratio", 0 ] } },
            { "patchline": { "source": [ "obj-v2-ratio", 0 ], "destination": [ "obj-v2-pfft", 1 ] } },
            { "patchline": { "source": [ "obj-v2-pfft", 0 ], "destination": [ "obj-v2-fmteq", 0 ] } },
            { "patchline": { "source": [ "obj-v2-fmt", 0 ], "destination": [ "obj-v2-fmtsig", 0 ] } },
            { "patchline": { "source": [ "obj-v2-fmtsig", 0 ], "destination": [ "obj-v2-fmteq", 1 ] } },
            { "patchline": { "source": [ "obj-v2-fmteq", 0 ], "destination": [ "obj-v2-mult", 0 ] } },
            { "patchline": { "source": [ "obj-v2-gain", 0 ], "destination": [ "obj-v2-dbtoa", 0 ] } },
            { "patchline": { "source": [ "obj-v2-dbtoa", 0 ], "destination": [ "obj-v2-mult", 1 ] } },
            { "patchline": { "source": [ "obj-v2-mult", 0 ], "destination": [ "obj-v2-delay", 0 ] } },
            { "patchline": { "source": [ "obj-v2-dly", 0 ], "destination": [ "obj-v2-dlysig", 0 ] } },
            { "patchline": { "source": [ "obj-v2-dlysig", 0 ], "destination": [ "obj-v2-ms2s", 0 ] } },
            { "patchline": { "source": [ "obj-v2-ms2s", 0 ], "destination": [ "obj-v2-delay", 1 ] } },
            { "patchline": { "source": [ "obj-v2-pan", 0 ], "destination": [ "obj-v2-ps", 0 ] } },
            { "patchline": { "source": [ "obj-v2-ps", 0 ], "destination": [ "obj-v2-phalf", 0 ] } },
            { "patchline": { "source": [ "obj-v2-phalf", 0 ], "destination": [ "obj-v2-poff", 0 ] } },
            { "patchline": { "source": [ "obj-v2-poff", 0 ], "destination": [ "obj-v2-panR", 1 ] } },
            { "patchline": { "source": [ "obj-v2-poff", 0 ], "destination": [ "obj-v2-invp", 0 ] } },
            { "patchline": { "source": [ "obj-v2-invp", 0 ], "destination": [ "obj-v2-panL", 1 ] } },
            { "patchline": { "source": [ "obj-v2-delay", 0 ], "destination": [ "obj-v2-panR", 0 ] } },
            { "patchline": { "source": [ "obj-v2-delay", 0 ], "destination": [ "obj-v2-panL", 0 ] } },

            { "patchline": { "source": [ "obj-v3-semi", 0 ], "destination": [ "obj-v3-ratio", 0 ] } },
            { "patchline": { "source": [ "obj-v3-ratio", 0 ], "destination": [ "obj-v3-pfft", 1 ] } },
            { "patchline": { "source": [ "obj-v3-pfft", 0 ], "destination": [ "obj-v3-fmteq", 0 ] } },
            { "patchline": { "source": [ "obj-v3-fmt", 0 ], "destination": [ "obj-v3-fmtsig", 0 ] } },
            { "patchline": { "source": [ "obj-v3-fmtsig", 0 ], "destination": [ "obj-v3-fmteq", 1 ] } },
            { "patchline": { "source": [ "obj-v3-fmteq", 0 ], "destination": [ "obj-v3-mult", 0 ] } },
            { "patchline": { "source": [ "obj-v3-gain", 0 ], "destination": [ "obj-v3-dbtoa", 0 ] } },
            { "patchline": { "source": [ "obj-v3-dbtoa", 0 ], "destination": [ "obj-v3-mult", 1 ] } },
            { "patchline": { "source": [ "obj-v3-mult", 0 ], "destination": [ "obj-v3-delay", 0 ] } },
            { "patchline": { "source": [ "obj-v3-dly", 0 ], "destination": [ "obj-v3-dlysig", 0 ] } },
            { "patchline": { "source": [ "obj-v3-dlysig", 0 ], "destination": [ "obj-v3-ms2s", 0 ] } },
            { "patchline": { "source": [ "obj-v3-ms2s", 0 ], "destination": [ "obj-v3-delay", 1 ] } },
            { "patchline": { "source": [ "obj-v3-pan", 0 ], "destination": [ "obj-v3-ps", 0 ] } },
            { "patchline": { "source": [ "obj-v3-ps", 0 ], "destination": [ "obj-v3-phalf", 0 ] } },
            { "patchline": { "source": [ "obj-v3-phalf", 0 ], "destination": [ "obj-v3-poff", 0 ] } },
            { "patchline": { "source": [ "obj-v3-poff", 0 ], "destination": [ "obj-v3-panR", 1 ] } },
            { "patchline": { "source": [ "obj-v3-poff", 0 ], "destination": [ "obj-v3-invp", 0 ] } },
            { "patchline": { "source": [ "obj-v3-invp", 0 ], "destination": [ "obj-v3-panL", 1 ] } },
            { "patchline": { "source": [ "obj-v3-delay", 0 ], "destination": [ "obj-v3-panR", 0 ] } },
            { "patchline": { "source": [ "obj-v3-delay", 0 ], "destination": [ "obj-v3-panL", 0 ] } },

            { "patchline": { "source": [ "obj-v4-semi", 0 ], "destination": [ "obj-v4-ratio", 0 ] } },
            { "patchline": { "source": [ "obj-v4-ratio", 0 ], "destination": [ "obj-v4-pfft", 1 ] } },
            { "patchline": { "source": [ "obj-v4-pfft", 0 ], "destination": [ "obj-v4-fmteq", 0 ] } },
            { "patchline": { "source": [ "obj-v4-fmt", 0 ], "destination": [ "obj-v4-fmtsig", 0 ] } },
            { "patchline": { "source": [ "obj-v4-fmtsig", 0 ], "destination": [ "obj-v4-fmteq", 1 ] } },
            { "patchline": { "source": [ "obj-v4-fmteq", 0 ], "destination": [ "obj-v4-mult", 0 ] } },
            { "patchline": { "source": [ "obj-v4-gain", 0 ], "destination": [ "obj-v4-dbtoa", 0 ] } },
            { "patchline": { "source": [ "obj-v4-dbtoa", 0 ], "destination": [ "obj-v4-mult", 1 ] } },
            { "patchline": { "source": [ "obj-v4-mult", 0 ], "destination": [ "obj-v4-delay", 0 ] } },
            { "patchline": { "source": [ "obj-v4-dly", 0 ], "destination": [ "obj-v4-dlysig", 0 ] } },
            { "patchline": { "source": [ "obj-v4-dlysig", 0 ], "destination": [ "obj-v4-ms2s", 0 ] } },
            { "patchline": { "source": [ "obj-v4-ms2s", 0 ], "destination": [ "obj-v4-delay", 1 ] } },
            { "patchline": { "source": [ "obj-v4-pan", 0 ], "destination": [ "obj-v4-ps", 0 ] } },
            { "patchline": { "source": [ "obj-v4-ps", 0 ], "destination": [ "obj-v4-phalf", 0 ] } },
            { "patchline": { "source": [ "obj-v4-phalf", 0 ], "destination": [ "obj-v4-poff", 0 ] } },
            { "patchline": { "source": [ "obj-v4-poff", 0 ], "destination": [ "obj-v4-panR", 1 ] } },
            { "patchline": { "source": [ "obj-v4-poff", 0 ], "destination": [ "obj-v4-invp", 0 ] } },
            { "patchline": { "source": [ "obj-v4-invp", 0 ], "destination": [ "obj-v4-panL", 1 ] } },
            { "patchline": { "source": [ "obj-v4-delay", 0 ], "destination": [ "obj-v4-panR", 0 ] } },
            { "patchline": { "source": [ "obj-v4-delay", 0 ], "destination": [ "obj-v4-panL", 0 ] } },

            { "patchline": { "source": [ "obj-v1-panL", 0 ], "destination": [ "obj-sumL1", 0 ] } },
            { "patchline": { "source": [ "obj-v2-panL", 0 ], "destination": [ "obj-sumL1", 1 ] } },
            { "patchline": { "source": [ "obj-sumL1", 0 ], "destination": [ "obj-sumL2", 0 ] } },
            { "patchline": { "source": [ "obj-v3-panL", 0 ], "destination": [ "obj-sumL2", 1 ] } },
            { "patchline": { "source": [ "obj-sumL2", 0 ], "destination": [ "obj-sumL3", 0 ] } },
            { "patchline": { "source": [ "obj-v4-panL", 0 ], "destination": [ "obj-sumL3", 1 ] } },

            { "patchline": { "source": [ "obj-v1-panR", 0 ], "destination": [ "obj-sumR1", 0 ] } },
            { "patchline": { "source": [ "obj-v2-panR", 0 ], "destination": [ "obj-sumR1", 1 ] } },
            { "patchline": { "source": [ "obj-sumR1", 0 ], "destination": [ "obj-sumR2", 0 ] } },
            { "patchline": { "source": [ "obj-v3-panR", 0 ], "destination": [ "obj-sumR2", 1 ] } },
            { "patchline": { "source": [ "obj-sumR2", 0 ], "destination": [ "obj-sumR3", 0 ] } },
            { "patchline": { "source": [ "obj-v4-panR", 0 ], "destination": [ "obj-sumR3", 1 ] } },

            { "patchline": { "source": [ "obj-sumL3", 0 ], "destination": [ "obj-addDryL", 0 ] } },
            { "patchline": { "source": [ "obj-dry-mult", 0 ], "destination": [ "obj-addDryL", 1 ] } },
            { "patchline": { "source": [ "obj-sumR3", 0 ], "destination": [ "obj-addDryR", 0 ] } },
            { "patchline": { "source": [ "obj-dry-mult", 0 ], "destination": [ "obj-addDryR", 1 ] } },

            { "patchline": { "source": [ "obj-dry-gain", 0 ], "destination": [ "obj-dry-dbtoa", 0 ] } },
            { "patchline": { "source": [ "obj-dry-dbtoa", 0 ], "destination": [ "obj-dry-mult", 1 ] } },

            { "patchline": { "source": [ "obj-addDryL", 0 ], "destination": [ "obj-masterL", 0 ] } },
            { "patchline": { "source": [ "obj-addDryR", 0 ], "destination": [ "obj-masterR", 0 ] } },
            { "patchline": { "source": [ "obj-master-val", 0 ], "destination": [ "obj-master-dbtoa", 0 ] } },
            { "patchline": { "source": [ "obj-master-dbtoa", 0 ], "destination": [ "obj-masterL", 1 ] } },
            { "patchline": { "source": [ "obj-master-dbtoa", 0 ], "destination": [ "obj-masterR", 1 ] } },

            { "patchline": { "source": [ "obj-masterL", 0 ], "destination": [ "obj-meterL", 0 ] } },
            { "patchline": { "source": [ "obj-masterR", 0 ], "destination": [ "obj-meterR", 0 ] } },
            { "patchline": { "source": [ "obj-masterL", 0 ], "destination": [ "obj-ezdac", 0 ] } },
            { "patchline": { "source": [ "obj-masterR", 0 ], "destination": [ "obj-ezdac", 1 ] } },

            { "patchline": { "source": [ "obj-key-menu", 0 ], "destination": [ "obj-harmony", 0 ] } },
            { "patchline": { "source": [ "obj-scale-menu", 0 ], "destination": [ "obj-harmony", 1 ] } },

            { "patchline": { "source": [ "obj-preset-woods", 0 ], "destination": [ "obj-presets", 0 ] } },
            { "patchline": { "source": [ "obj-preset-choir", 0 ], "destination": [ "obj-presets", 1 ] } },
            { "patchline": { "source": [ "obj-preset-shimmer", 0 ], "destination": [ "obj-presets", 2 ] } },
            { "patchline": { "source": [ "obj-preset-dark", 0 ], "destination": [ "obj-presets", 3 ] } },
            { "patchline": { "source": [ "obj-presets", 0 ], "destination": [ "obj-route-presets", 0 ] } },

            { "patchline": { "source": [ "obj-route-presets", 0 ], "destination": [ "obj-v1-semi", 0 ] } },
            { "patchline": { "source": [ "obj-route-presets", 1 ], "destination": [ "obj-v2-semi", 0 ] } },
            { "patchline": { "source": [ "obj-route-presets", 2 ], "destination": [ "obj-v3-semi", 0 ] } },
            { "patchline": { "source": [ "obj-route-presets", 3 ], "destination": [ "obj-v4-semi", 0 ] } },
            { "patchline": { "source": [ "obj-route-presets", 4 ], "destination": [ "obj-v1-fmt", 0 ] } },
            { "patchline": { "source": [ "obj-route-presets", 5 ], "destination": [ "obj-v2-fmt", 0 ] } },
            { "patchline": { "source": [ "obj-route-presets", 6 ], "destination": [ "obj-v3-fmt", 0 ] } },
            { "patchline": { "source": [ "obj-route-presets", 7 ], "destination": [ "obj-v4-fmt", 0 ] } },
            { "patchline": { "source": [ "obj-route-presets", 8 ], "destination": [ "obj-v1-gain", 0 ] } },
            { "patchline": { "source": [ "obj-route-presets", 9 ], "destination": [ "obj-v2-gain", 0 ] } },
            { "patchline": { "source": [ "obj-route-presets", 10 ], "destination": [ "obj-v3-gain", 0 ] } },
            { "patchline": { "source": [ "obj-route-presets", 11 ], "destination": [ "obj-v4-gain", 0 ] } },
            { "patchline": { "source": [ "obj-route-presets", 12 ], "destination": [ "obj-v1-dly", 0 ] } },
            { "patchline": { "source": [ "obj-route-presets", 13 ], "destination": [ "obj-v2-dly", 0 ] } },
            { "patchline": { "source": [ "obj-route-presets", 14 ], "destination": [ "obj-v3-dly", 0 ] } },
            { "patchline": { "source": [ "obj-route-presets", 15 ], "destination": [ "obj-v4-dly", 0 ] } },
            { "patchline": { "source": [ "obj-route-presets", 16 ], "destination": [ "obj-v1-pan", 0 ] } },
            { "patchline": { "source": [ "obj-route-presets", 17 ], "destination": [ "obj-v2-pan", 0 ] } },
            { "patchline": { "source": [ "obj-route-presets", 18 ], "destination": [ "obj-v3-pan", 0 ] } },
            { "patchline": { "source": [ "obj-route-presets", 19 ], "destination": [ "obj-v4-pan", 0 ] } },
            { "patchline": { "source": [ "obj-route-presets", 20 ], "destination": [ "obj-dry-gain", 0 ] } }
        ],
        "autosave": 0
    }
}
